name: feature-01 CI
run-name: ${{ github.actor }} is feature
on:
  push: 
    branchs: 
      - feature-01
jobs: 
  ci-feature-01: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
        with:
          token: ${{ github.token }} 
      - uses: actions/setup-node@v3
        with:
          node-version: "16" 
      - name: setup-git
        run: |
          git config --global user.email "${{ github.event.pusher.email }}"
          git config --global user.name "${{ github.actor }}" 
      - name: Install Packages
        run: npm install
      - name: Install deprndencies
        run: npm ci
      - name: Test Project
        run: npm run test
      - name: Merge to main
        run: |
          git fetch --unshallow
          git checkout main
          git merge main