name: deploy-manual-gh-pages-actions
run-name: ${{ github.actor }} is deploying gh-pages manually
on:
  push: 
    branchs: 
      - main
jobs: 
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
        with:
          token: ${{ github.token }}
      - uses: actions/setup-node@v3
        with:
          node-version: "16" 
      - name: setup git
        run: |
          git config --global user.email "${{ github.event.pusher.email }}"
          git config --global user.name "${{ github.actor }}" 
      - name: Install Packages
        run: npm install
      - name: Build project
        run: PUBLIC_URL=/${{ github.event.repository.name }} npm run build
      - name: deploy
        run: |
          # mkdir ./gh-pages
          cd ./build
          git init -b gh-pages ./gh-pages
          # cd ./gh-pages
          git remote add -t gh-pages origin \
          https://git:${{ github.token }}@github.com/${{ github.repository }}.git 
          git fetch -u origin gh-pages:gh-pages
          # git pull origin gh-pages
          # rm -rf ./*
          # cp -rf ../build/* ./
          git add .
          git commit -m "Manually deploy"
          git push origin gh-pages -f
          cd ..
      
      